#Github Hosts Start
#Update Time: 2023-11-05
#Project Address: https://github.com/maxiaof/github-hosts
#Update URL: https://raw.githubusercontent.com/maxiaof/github-hosts/master/hosts
alive.github.com = 140.82.113.25
live.github.com = 140.82.114.26
github.githubassets.com = 185.199.109.154
central.github.com = 140.82.113.21
desktop.githubusercontent.com = 185.199.109.133
assets-cdn.github.com = 185.199.109.153
camo.githubusercontent.com = 185.199.111.133
github.map.fastly.net = 185.199.110.133
github.global.ssl.fastly.net = 146.75.121.194
gist.github.com = 140.82.121.3
github.io = 185.199.110.153
github.com = 140.82.121.3
github.blog = 192.0.66.2
api.github.com = 140.82.121.5
raw.githubusercontent.com = 185.199.109.133
user-images.githubusercontent.com = 185.199.110.133
favicons.githubusercontent.com = 185.199.109.133
avatars5.githubusercontent.com = 185.199.110.133
avatars4.githubusercontent.com = 185.199.109.133
avatars3.githubusercontent.com = 185.199.108.133
avatars2.githubusercontent.com = 185.199.109.133
avatars1.githubusercontent.com = 185.199.109.133
avatars0.githubusercontent.com = 185.199.111.133
avatars.githubusercontent.com = 185.199.111.133
codeload.github.com = 140.82.121.10
github-cloud.s3.amazonaws.com = 52.217.132.81
github-com.s3.amazonaws.com = 52.216.152.108
github-production-release-asset-2e65be.s3.amazonaws.com = 52.217.129.137
github-production-user-asset-6210df.s3.amazonaws.com = 3.5.29.202
github-production-repository-file-5c1aeb.s3.amazonaws.com = 52.216.210.177
githubstatus.com = 185.199.108.153
github.community = 140.82.112.18
github.dev = 51.137.3.17
collector.github.com = 140.82.113.22
pipelines.actions.githubusercontent.com = 13.107.42.16
media.githubusercontent.com = 185.199.111.133
cloud.githubusercontent.com = 185.199.111.133
objects.githubusercontent.com = 185.199.109.133
#Github Hosts End